Improve 'check' error message when no Lisp is installed
Ignore-this: 809ad83dcc86129a15e9b9403e0def0

darcs-hash:20100102212808-7272b-c74f439e4956f309ac7c3d4856626edbfac090b6.gz

diff --git a/clbuild b/clbuild
--- a/clbuild
+++ b/clbuild
@@ -1277,7 +1277,11 @@ check() {
 	
     echo
     echo "Checking Lisp startup..."
-    if ${lisp} $run_options $eval $quit >/dev/null; then
+    if ! test -e "${lisp}"; then
+      echo "Error: Don't have a Lisp system to bootstrap from."
+      echo "Please install e.g. ${implementation} and try again."
+      exit 1
+    elif ${lisp} $run_options $eval $quit >/dev/null; then
 	echo "Success: Lisp starts up using \"$lisp\""
     else
 	echo "Error: Cannot run Lisp using \"$lisp\""
