mention beagle in clbuild.conf.default
darcs-hash:20071221221954-e47ce-071ae5c39c19c0c5bfac772030310eafdee6c0fc.gz

diff --git a/clbuild b/clbuild
--- a/clbuild
+++ b/clbuild
@@ -80,7 +80,7 @@ case x$CLIM_BACKEND in
 	maybe_load_clx="(unless (find-package :xlib) (asdf:operate 'asdf:load-op :clx))"
         ;;
     *)
-        echo "invalid $CLIM_BACKEND, expected clx, gtkairo, or graphic-forms." 1>&2
+        echo "invalid $CLIM_BACKEND, see clbuild.conf.default for examples." 1>&2
         exit 1
         ;;
 esac
