Replaced clbuild/update.sh with clbuild/projects
New file projects in a declarative syntax.

Folded the shell code from update.sh back into clbuild.

$all_projects now computed from the projects file.

darcs-hash:20071221214016-e47ce-0275fc09259670670864b15a4fae9599fe6677e2.gz

diff --git a/clbuild b/clbuild
--- a/clbuild
+++ b/clbuild
@@ -19,16 +19,6 @@
 
 set -e
 
-all_projects="flexichain mcclim zip cxml closure gsharp climacs slime beirc
-eclipse cl+ssl trivial-gray-streams usocket cl-irc cl-ppcre flexi-streams
-cl-fad hunchentoot chunga url-rewrite cl-who cl-webdav clx cffi
-bordeaux-threads climplayer closer-mop lw-compat skippy salza puri midi md5
-cl-base64 spatial-trees trivial-sockets split-sequence rfc2388
-graphic-forms closure-common closure-html cxml-rng cxml-stp drakma babel
-alexandria trivial-features clsql rt psgraph cl-pdf plexippus-xpath
-cl-yacc parse-number cl-typesetting acl-compat mel-base clim-alerts
-net-telent-date"
-
 if [ "$CLNET_USER" == "" ]; then
     CLNET_USER=:pserver:anonymous:anonymous
 fi
@@ -60,7 +50,19 @@ make_absolute_pn() {
 		echo "$(cd "$(dirname "$1")" ; pwd)/$(basename "$1")")
 	fi
 }
-UPDATE_SCRIPT="$(make_absolute_pn "$UPDATE_SCRIPT")"
+case $UPDATE_SCRIPT in
+    update_project)
+	# okay, new name
+	;;
+    update.sh)
+	# old name
+	UPDATE_SCRIPT=update_project
+	;;
+    *)
+	# do will still want this?
+	UPDATE_SCRIPT="$(make_absolute_pn "$UPDATE_SCRIPT")"
+	;;
+esac
 USER_INIT="$(make_absolute_pn "$USER_INIT")"
 
 if test -n "$windowsp" -a x$USER_INIT = x/dev/null; then
@@ -265,6 +267,275 @@ count_systems() {
 	echo "$n_asd system definition files registered"
 }
 
+blank_line="                                                                  "
+tail_last() {
+    if tty 0>&1 >/dev/null; then
+	while read line; do
+	    echo -e '\r\c'
+	    echo -n "$blank_line"
+	    echo -e '\r\c'
+	    echo -n $line | cut -b 1-65 | tr -d '\n'
+	done
+	echo -e '\r\c'
+	echo -n "$blank_line"
+	echo -e '\r\c'
+    else
+	while read line; do
+	    echo $line
+	done
+    fi
+}
+
+dribble_get() {
+    label="$1"
+    name="$2"
+
+    if test -d `echo ${name}*/ | awk '{print $1;}'`; then
+	echo -n "UPDATE "
+    else
+	echo -n "NEW "
+    fi
+    echo "$label $name"
+}
+
+dry_run_ok() {
+   if test -n "$dry_run"; then
+       echo "OK: $1"
+   fi
+}
+
+dry_run_missing() {
+   if test -n "$dry_run"; then
+       echo "MISSING: $1"
+   fi
+}
+
+get_darcs() {
+    name="$1"
+    url="$2"
+
+    if [ -d $name ]; then
+	actual="`cat $name/_darcs/prefs/defaultrepo`"
+	if test "x$actual" = "x$url"; then
+	    dry_run_ok $1
+	else
+	    echo "MISMATCH: $1 was installed from $actual, current is $url"
+	fi
+    else
+	dry_run_missing $1
+    fi
+    if test -n "$dry_run"; then
+	exit 0
+    fi
+
+    # don't use tail_last, since darcs already has this kind of progress bar
+    if [ -d $name ]; then
+	dribble_get "darcs pull" $name
+	(
+	    cd $name
+	    if ! test -d _darcs; then
+		echo ERROR: not a darcs repository
+		exit 1
+	    fi
+	    darcs pull --all
+	    )
+    else
+	dribble_get "darcs get" $name
+	darcs get $url $name
+    fi
+}
+
+get_git() {
+    name="$1"
+    url="$2"
+
+    if [ -d $name ]; then
+	actual="`cd $name && git config --get remote.origin.url`"
+	if test "x$actual" = "x$url"; then
+	    dry_run_ok $1
+	else
+	    echo "MISMATCH: $1 was installed from $actual, current is $url"
+	fi
+    else
+	dry_run_missing $1
+    fi
+    if test -n "$dry_run"; then
+	exit 0
+    fi
+
+    if [ -d $name ]; then
+	dribble_get "git pull" $name
+	(
+	    cd $name
+	    if ! test -d .git; then
+		echo ERROR: not a darcs repository
+		exit 1
+	    fi
+	    git pull
+	    )
+    else
+	dribble_get "git clone" $name
+	git clone $url $name
+    fi
+}
+
+get_svn() {
+    name="$1"
+    url="$2"
+
+    if [ -d $name ]; then
+	actual="`cd $name && svn info | grep ^URL: | awk '{print $2;}'`"
+	if test "x$actual" = "x$url"; then
+	    dry_run_ok $1
+	else
+	    echo "MISMATCH: $1 was installed from $actual, current is $url"
+	fi
+    else
+	dry_run_missing $1
+    fi
+    if test -n "$dry_run"; then
+	exit 0
+    fi
+
+    dribble_get "svn co" $name
+
+    svn co $url $name | tail_last
+}
+
+get_cvs_aux() {
+    module="$1"
+    repository="$2"
+    target_directory="$3"
+
+    if [ -d $module ]; then
+	actual="`cat $module/CVS/Root`"
+	if test "x$actual" = "x$repository"; then
+	    dry_run_ok $1
+	else
+	    echo "MISMATCH: $1 was installed from $actual, current is $repository"
+	fi
+    else
+	dry_run_missing $1
+    fi
+    if test -n "$dry_run"; then
+	exit 0
+    fi
+
+    dribble_get "cvs co" $module
+
+    cvs -d $repository co ${3+-d "$3"} $module | tail_last
+}
+
+get_cvs_full() {
+    get_cvs_aux $3 $2 $1
+}
+
+get_tarball() {
+    name="$1"
+    url="$2"
+    flags="${3:-z}"
+
+    echo "Warning: Using deprecated method get_tarball."
+
+    if test -n "$dry_run"; then
+	if ls -d ${name}* >/dev/null; then
+	    directories="`ls -d ${name}*`"
+	    echo "TARBALL: $directories installed from a tarball, cannot check"
+	else
+	    dry_run_missing $1
+	fi
+	exit 0
+    fi
+
+    tmp=$TMPDIR/${name}.tar.gz
+
+    dribble_get wget $name
+
+    # We used to delete old directories completely here.  Unfortunately,
+    # that can easily lead to loss of changes, a problem all the VC checkout
+    # method do not have to the extent.  Save all old data instead.  Users
+    # can delete the resulting backup directories easily enough themselves.
+    if ls ${name}* >/dev/null; then
+	echo got here
+	backup=`mktemp -d backup_${name}_XXXXXXXXXX`
+	mv ${name}* "$backup/"
+    fi
+    wget \
+	--no-check-certificate \
+	--progress=dot \
+	-O "$tmp" \
+	$url \
+	2>&1 | tail_last
+    tar v${flags}xf "$tmp" | tail_last
+    rm "$tmp"
+}
+
+get_svn_clnet() {
+    name="$1"
+    path="$2"
+
+    get_svn $name svn://common-lisp.net/project/$name/svn/$2
+}
+
+get_cvs_clnet() {
+    module="$1"
+    project="${2:-$1}"
+
+    get_cvs_aux $module ${CLNET_USER}@common-lisp.net:/project/$project/cvsroot
+}
+
+get_ediware() {
+    get_darcs $1 http://common-lisp.net/~loliveira/ediware/$1
+}
+
+get_clbuild_mirror() {
+    get_darcs $1 http://common-lisp.net/project/clbuild/mirror/$1
+}
+
+get_lichteblau_com() {
+    get_git $1 http://www.lichteblau.com/git/$1.git
+}
+
+get_b9_com() {
+    get_git $1 http://git.b9.com/$1.git
+}
+
+get_tarball_bz2() {
+    get_tarball "$1" "$2" j
+}
+
+update_project() {
+    if test x$1 = x--dry-run; then
+	shift
+	dry_run=1
+    else
+	unset dry_run
+    fi
+    export dry_run
+
+    if test $# -ne 1; then
+	exec 1>&2
+	echo error: invalid number of arguments
+	echo usage: ... update [--dry-run] PROJECT_NAME
+	exit 1
+    fi
+
+    if ! grep "^$1 " "$BASE/projects" >/dev/null; then
+       echo Error: cannot download unknown project $1
+       exit 1
+    fi
+    found=`grep "^$1 " "$BASE/projects"`
+    update_project_2 $found
+}
+
+update_project_2() {
+    name="$1"
+    action="$2"
+    shift
+    shift
+    ( $action $name "$@" )
+}
+
 update() {
 	rm -f "$BASE"/monster.core
 
@@ -277,7 +548,6 @@ update() {
         trap cleanup exit
 
 	cd "$source_dir"
-	chmod +x ../update.sh
 
 	projects="$all_projects"
 	if test -n "$1"; then
@@ -580,6 +850,12 @@ if test -f "$BASE"/monster.core; then
     run_options="$core_option "$BASE"/monster.core $run_options"
 fi
 
+all_projects=`cat "$BASE/projects" | awk '{print $1;}' | while read name; do
+	if test x"$name" != 'x#'; then
+	    echo -n "$name "
+	fi
+    done`
+
 case $1 in
     check)
 	check
@@ -728,7 +1004,6 @@ case $1 in
 	;;
     check-urls)
 	cd "$source_dir"
-	chmod +x ../update.sh
 	for project in ${2:-$all_projects}; do
 	    ${UPDATE_SCRIPT} --dry-run $project
 	done
